Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /Users/zixuanyan/PycharmProjects/untitled
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          YELP_KEY: eC-Eo7JXvVrtx9s7ZThdF-55zDI3eH1vskl-iYyQpWW3sheeNznO2Zh5Nj3gcoGHlcDQUkDpDtwcniicPRUFxtqIoO5WqPsEeNjYtzyDD4z3KrERl4KPoLxpE415Y3Yx
          YELP_URL: https://api.yelp.com/v3/businesses/search